// src/lib/mock-data.ts
import { StockSignal, WatchlistItem, Alert, TrendingStock, SignalHistory, SourceData } from "@/types";

export const mockSignals: StockSignal[] = [
  {
    id: "1",
    ticker: "AAPL",
    name: "Apple Inc.",
    signal: "buy",
    confidence: 87,
    price: 195.42,
    change: 2.34,
    changePercent: 1.21,
    summary: "iPhone 16 announcement buzz driving positive sentiment across YouTube and Twitter",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 15),
    sources: { youtube: 4, twitter: 6, reddit: 2 },
    factors: [
      { type: "positive", label: "YouTube Sentiment", value: "+42%" },
      { type: "positive", label: "Twitter Mentions", value: "+156%" },
      { type: "neutral", label: "Reddit Sentiment", value: "Mixed" },
      { type: "positive", label: "Price Action", value: "Above 20 MA" },
    ],
  },
  {
    id: "2",
    ticker: "TSLA",
    name: "Tesla, Inc.",
    signal: "hold",
    confidence: 52,
    price: 248.12,
    change: -1.98,
    changePercent: -0.79,
    summary: "Mixed reactions to FSD demo with debates on timeline and capabilities",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 30),
    sources: { youtube: 3, twitter: 8, reddit: 4 },
    factors: [
      { type: "positive", label: "YouTube Coverage", value: "High" },
      { type: "negative", label: "Twitter Sentiment", value: "-12%" },
      { type: "neutral", label: "Reddit Discussion", value: "Debate" },
      { type: "negative", label: "Price Action", value: "Below 50 MA" },
    ],
  },
  {
    id: "3",
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    signal: "buy",
    confidence: 92,
    price: 892.34,
    change: 45.67,
    changePercent: 5.39,
    summary: "Earnings beat expectations with strong AI demand commentary",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 5),
    sources: { youtube: 6, twitter: 12, reddit: 5 },
    factors: [
      { type: "positive", label: "Earnings Reaction", value: "Beat" },
      { type: "positive", label: "AI Demand", value: "Strong" },
      { type: "positive", label: "YouTube Coverage", value: "Bullish" },
      { type: "positive", label: "Twitter Sentiment", value: "+89%" },
    ],
  },
  {
    id: "4",
    ticker: "GME",
    name: "GameStop Corp.",
    signal: "buy",
    confidence: 78,
    price: 24.82,
    change: 3.45,
    changePercent: 16.14,
    summary: "Roaring Kitty tweet sparked massive social media momentum",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 10),
    sources: { youtube: 2, twitter: 25, reddit: 18 },
    factors: [
      { type: "positive", label: "Viral Content", value: "Detected" },
      { type: "positive", label: "Reddit Activity", value: "+520%" },
      { type: "positive", label: "Twitter Mentions", value: "+340%" },
      { type: "neutral", label: "Risk Level", value: "High Volatility" },
    ],
  },
  {
    id: "5",
    ticker: "AMC",
    name: "AMC Entertainment",
    signal: "sell",
    confidence: 72,
    price: 4.82,
    change: -0.18,
    changePercent: -3.60,
    summary: "Meme momentum fading with declining social engagement",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 45),
    sources: { youtube: 1, twitter: 8, reddit: 6 },
    factors: [
      { type: "negative", label: "Social Volume", value: "-28%" },
      { type: "negative", label: "Reddit Sentiment", value: "Bearish" },
      { type: "negative", label: "Price Action", value: "Breakdown" },
      { type: "neutral", label: "YouTube Coverage", value: "Minimal" },
    ],
  },
  {
    id: "6",
    ticker: "AMD",
    name: "Advanced Micro Devices",
    signal: "sell",
    confidence: 65,
    price: 142.56,
    change: -4.23,
    changePercent: -2.88,
    summary: "Competitive pressure from NVIDIA affecting sentiment",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 20),
    sources: { youtube: 3, twitter: 7, reddit: 3 },
    factors: [
      { type: "negative", label: "Competitive Risk", value: "High" },
      { type: "negative", label: "YouTube Sentiment", value: "-15%" },
      { type: "neutral", label: "Twitter Mentions", value: "Stable" },
      { type: "negative", label: "Market Share", value: "Concerns" },
    ],
  },
  {
    id: "7",
    ticker: "BTC",
    name: "Bitcoin",
    signal: "buy",
    confidence: 71,
    price: 52134.89,
    change: 1234.56,
    changePercent: 2.42,
    summary: "ETF inflows continuing with positive institutional commentary",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 12),
    sources: { youtube: 5, twitter: 15, reddit: 8 },
    factors: [
      { type: "positive", label: "ETF Flows", value: "Strong" },
      { type: "positive", label: "Institutional", value: "Buying" },
      { type: "positive", label: "YouTube Sentiment", value: "+34%" },
      { type: "neutral", label: "Regulatory", value: "Stable" },
    ],
  },
];

export const mockWatchlist: WatchlistItem[] = [
  { id: "1", ticker: "AAPL", name: "Apple Inc.", folder: "Tech Stocks", order: 0, unreadAlerts: 0 },
  { id: "2", ticker: "NVDA", name: "NVIDIA Corporation", folder: "Tech Stocks", order: 1, unreadAlerts: 1 },
  { id: "3", ticker: "TSLA", name: "Tesla, Inc.", folder: "Tech Stocks", order: 2, unreadAlerts: 0 },
  { id: "4", ticker: "AMD", name: "Advanced Micro Devices", folder: "Tech Stocks", order: 3, unreadAlerts: 0 },
  { id: "5", ticker: "GME", name: "GameStop Corp.", folder: "Meme Stocks", order: 0, unreadAlerts: 2 },
  { id: "6", ticker: "AMC", name: "AMC Entertainment", folder: "Meme Stocks", order: 1, unreadAlerts: 0 },
  { id: "7", ticker: "BTC", name: "Bitcoin", folder: "Crypto", order: 0, unreadAlerts: 0 },
];

export const mockAlerts: Alert[] = [
  {
    id: "1",
    type: "signal_change",
    ticker: "NVDA",
    title: "BUY Signal Triggered",
    message: "NVDA confidence jumped to 82% following earnings beat",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    data: { previousSignal: "hold", newSignal: "buy", confidenceChange: 35 },
  },
  {
    id: "2",
    type: "viral_content",
    ticker: "GME",
    title: "Viral Content Detected",
    message: "RoaringKitty posted a tweet causing massive social momentum",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "3",
    type: "confidence_jump",
    ticker: "AAPL",
    title: "Confidence Jump",
    message: "AAPL confidence increased by 25% in the last hour",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    data: { confidenceChange: 25 },
  },
  {
    id: "4",
    type: "signal_change",
    ticker: "AMC",
    title: "SELL Signal",
    message: "AMC sentiment dropped 28%, triggering sell signal",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    data: { previousSignal: "hold", newSignal: "sell", confidenceChange: -18 },
  },
  {
    id: "5",
    type: "influencer_mention",
    ticker: "TSLA",
    title: "Influencer Mention",
    message: "@ElonMusk posted bullish commentary on Tesla FSD",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
];

export const mockTrending: TrendingStock[] = [
  { rank: 1, ticker: "NVDA", name: "NVIDIA Corporation", signal: "buy", confidence: 92, sentimentChange: 45, mentionCount: 12400, mentionChange: 340, reason: "Earnings beat expectations" },
  { rank: 2, ticker: "GME", name: "GameStop Corp.", signal: "buy", confidence: 78, sentimentChange: 38, mentionCount: 8700, mentionChange: 520, reason: "Roaring Kitty tweet" },
  { rank: 3, ticker: "TSLA", name: "Tesla, Inc.", signal: "hold", confidence: 52, sentimentChange: 5, mentionCount: 6200, mentionChange: 12, reason: "FSD demo mixed reviews" },
  { rank: 4, ticker: "BTC", name: "Bitcoin", signal: "buy", confidence: 71, sentimentChange: 18, mentionCount: 5800, mentionChange: 89, reason: "ETF inflows continue" },
  { rank: 5, ticker: "AAPL", name: "Apple Inc.", signal: "buy", confidence: 87, sentimentChange: 22, mentionCount: 4500, mentionChange: 156, reason: "iPhone 16 buzz" },
  { rank: 6, ticker: "AMC", name: "AMC Entertainment", signal: "sell", confidence: 72, sentimentChange: -28, mentionCount: 3200, mentionChange: -45, reason: "Meme momentum fading" },
  { rank: 7, ticker: "AMD", name: "Advanced Micro Devices", signal: "sell", confidence: 65, sentimentChange: -15, mentionCount: 2800, mentionChange: -12, reason: "NVIDIA competitive pressure" },
  { rank: 8, ticker: "PLTR", name: "Palantir Technologies", signal: "buy", confidence: 68, sentimentChange: 24, mentionCount: 2400, mentionChange: 89, reason: "Government contract news" },
  { rank: 9, ticker: "RIVN", name: "Rivian Automotive", signal: "hold", confidence: 48, sentimentChange: 8, mentionCount: 1900, mentionChange: 34, reason: "Production update" },
  { rank: 10, ticker: "COIN", name: "Coinbase Global", signal: "buy", confidence: 73, sentimentChange: 19, mentionCount: 1600, mentionChange: 67, reason: "Crypto momentum" },
];

export const mockSignalHistory: SignalHistory[] = [
  { id: "1", ticker: "NVDA", signal: "buy", confidence: 85, priceAtSignal: 846.67, priceAfter7Days: 945.12, result: "win", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7) },
  { id: "2", ticker: "TSLA", signal: "buy", confidence: 72, priceAtSignal: 248.12, priceAfter7Days: 242.10, result: "loss", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5) },
  { id: "3", ticker: "AAPL", signal: "buy", confidence: 78, priceAtSignal: 189.45, priceAfter7Days: 195.42, result: "win", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3) },
  { id: "4", ticker: "AMD", signal: "sell", confidence: 68, priceAtSignal: 146.79, priceAfter7Days: 142.56, result: "win", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2) },
  { id: "5", ticker: "GME", signal: "buy", confidence: 75, priceAtSignal: 21.37, priceAfter7Days: 24.82, result: "win", createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1) },
];

export const mockSources: SourceData[] = [
  { id: "1", type: "youtube", title: "Why I'm Buying MORE Apple Stock", author: "Meet Kevin", url: "#", sentiment: 0.82, publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 2), engagement: 450000, snippet: "Apple's iPhone 16 announcement is a game changer..." },
  { id: "2", type: "youtube", title: "Apple Stock Analysis 2024", author: "Graham Stephan", url: "#", sentiment: 0.75, publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 5), engagement: 320000, snippet: "The fundamentals remain strong despite market volatility..." },
  { id: "3", type: "twitter", title: "Apple's AI integration is impressive", author: "@techanalyst", url: "#", sentiment: 0.88, publishedAt: new Date(Date.now() - 1000 * 60 * 30), engagement: 12500, snippet: "The new neural engine capabilities are a massive step forward..." },
  { id: "4", type: "twitter", title: "Loading up on $AAPL calls", author: "@traderjoe", url: "#", sentiment: 0.91, publishedAt: new Date(Date.now() - 1000 * 60 * 45), engagement: 8700 },
  { id: "5", type: "reddit", title: "AAPL DD - Why I'm Bullish", author: "u/investor123", url: "#", sentiment: 0.68, publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 3), engagement: 2300, snippet: "Been holding since 2019, not selling now..." },
  { id: "6", type: "reddit", title: "iPhone 16 Leaks Discussion", author: "u/applefan", url: "#", sentiment: 0.45, publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6), engagement: 1200 },
];
